In [1]:
import csv
import numpy as np

In [6]:
with open("train.csv") as csvfile:
    raw = csv.reader(csvfile)
    rawlist = []
    for row in raw:
        rawlist.append(row)
    npdata = np.array(rawlist[1:], dtype = np.float32)
npdata = npdata[:, 1:]
print("Shape {}".format(npdata.shape))

Shape (2400, 13)


In [8]:
import tensorflow as tf
embedding_var = tf.Variable(npdata)
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver.save(sess, "./data.ckpt")

Instructions for updating:
Colocations handled automatically by placer.


In [22]:
#TRY TO SPLIT DATA INTO 11 CLUSTERS
a = np.sum((npdata[2371] - npdata[2399])**2)
print("Minimum euclid distance: {}".format(a))
from sklearn.cluster import DBSCAN
clustering = DBSCAN().fit_predict(npdata)
print(clustering)
print(set(clustering))
list(clustering).index(-1)
with open("labels.tsv", "w") as f:
    for line in np.array(clustering):
        f.write(str(line) + "\n")



Minimum euclid distance: 6023.99951171875
[0 1 2 ... 4 0 4]
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, -1}
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
Xtrain = npdata[:,:11]
Yregressiontrain = npdata[:,11:]
Yclustertrain = np.zeros((clustering.shape[0], len(set(clustering))))
for i in range(len(clustering)):
    Yclustertrain[i, clustering[i]] = 1
print(Xtrain.shape)
print(Yregressiontrain.shape)
print(Yclustertrain.shape)
np.save("Xtrain.npy", Xtrain)
np.save("Yregressiontrain.npy", Yregressiontrain)
np.save("Yclustertrain.npy", Yclustertrain)

(2400, 11)
(2400, 2)
(2400, 19)
